### ISSUE TITLE
What do you consider essential bussiness?

### ISSUE THREAD

**Issue by yizongk** [zhik/whats-open-north-brooklyn#1]
Does store like deli counts? Is the purpose of this repo to add in places that you know are opened?

**Comment by zhik** [comment]
Yes there are a ton of business that are captured. This is stored on an [airtable](https://airtable.com/shrRBozfbknHIlpIm/tblO0CoQECxUILlN3/viwYEcl1ku1Wzoqr0) 

This repo stores the code that serves the data. If you would like to add points or edit fill out the [form ](https://airtable.com/shrGc92OIWFQoSf5X). Note this is a North Brooklyn, we are expanding to Queens soon.

**Comment by yizongk** [comment]
Ahh okay thanks. I will close this issue
